### ISSUE TITLE
カメラの生成・設定が動作しない

### ISSUE THREAD

**Issue by dff9th** [akashic-games/akashic-engine#275]
フレームワーク利用者による問い合わせ先がわからなかったためこちらにて失礼します．

## 環境
- akashic-engine: v3.0.4
- 言語: typescript

## 事象
- 入門ガイド通りにカメラの設定を行おうとしたが，コンストラクタの仕様が異なっており`game`パラメータを指定できない．
- `game`パラメータを指定せず生成したカメラを`g.Game`に設定しても動作しない．（`getter`でも`undefined`が返ってくる）

## 例
```ts
const camera = new g.Camera2D({});  // 'game'パラメータは指定不可
g.game.focusingCamera = camera;
console.debug(g.game.focusingCamera);  // 'undefined'
```

## 参考資料
- 入門ガイド: https://akashic-games.github.io/tutorial/v3/multiplay/camera.html
- `Camera2D`のリファレンス: https://akashic-games.github.io/reference/akashic-engine-v3/classes/camera2d.html

**Comment by dff9th** [comment]
`akashic-sandbox`にて実行していましたが，`akashic serve`コマンドで実行したところカメラの正常動作を確認できたためCloseします．

**Comment by dera-** [comment]
closeいただいていますが、回答致します。


> 入門ガイド通りにカメラの設定を行おうとしたが，コンストラクタの仕様が異なっておりgameパラメータを指定できない．

公式ページの表記が誤っていました、ご迷惑をおかけして申し訳ございません。こちら修正対応を行おうと思います、ご報告ありがとうございます。
補足させていただきますと、akashic-engine v2 までは `g.Camera2D` のインスタンス生成時に game パラメータの指定が必要でしたが、akashic-engine v3 からはこの指定は不要となりました。

> gameパラメータを指定せず生成したカメラをg.Gameに設定しても動作しない．（getterでもundefinedが返ってくる）

現在 akashic-sandboxでは `g.game.focusingCamera` の指定ができない状態となっています(こちら既知の問題で修正予定ではあります)。こちらについてもご迷惑をおかけして申し訳ございません。
上記で仰られたように、`akashic serve` では動作致しますので、akashic-sandbox の代わりに `akashic serve` をご利用いただければと思います。
