### ISSUE TITLE
再生中のAudioAssetを別Sceneでロードできない

### ISSUE THREAD

**Issue by dff9th** [akashic-games/akashic-engine#329]
一般ユーザによる問い合わせ先がこちらでなかったらすみません。
掲題は大分かい摘んでいるので以下に詳細を記します。
推奨する対処方法があれば教えていただきたいです。

## 環境
- Node: `16.13.1`
- akashic-engin: `3.2.2`
- akashic-cli: `2.14.29`
- モード: `multi`
- 実行コマンド: `akashic serve -s nicolive`

## エラーメッセージ（Chrome）
```
Uncaught AssertionError: AssetManager#peekLiveAssetByAccessorPath(): No audio asset for /assets/audio/se
    at Object.createAssertionError (engineFilesV3_1_4.js:1)
    at AssetManager.peekLiveAssetByAccessorPath (engineFilesV3_1_4.js:1)
    at AssetAccessor.getAudio (engineFilesV3_1_4.js:1)
    at main.js:32
    at Trigger.fire (engineFilesV3_1_4.js:1)
    at Scene._fireLoaded (engineFilesV3_1_4.js:1)
    at Game._flushPostTickTasks (engineFilesV3_1_4.js:1)
    at Game.tick (engineFilesV3_1_4.js:1)
    at Game.game.tick (ServeGameContent.ts:101)
    at GameLoop._onFrameNormal (engineFilesV3_1_4.js:1)
```

## 条件（以下を全て満たす）
- 1つ目のSceneでAudioAssetを再生
- 再生中に2つ目のSceneに移行
- 2つ目のSceneではAudioAssetを読み込ませない
- 再生中に3つ目のSceneに移行
- 3つ目のSceneではAudioAssetを読み込ませる
- 3つ目のSceneでAudioAssetを取得する

## 再現コード
※`/assets/audio/se`は3秒以上の音声ファイル
```typescript
export = function main(): void {
  const scene1 = new g.Scene({
    game: g.game,
    assetPaths: ["/assets/audio/se"],
  });

  const scene2 = new g.Scene({
    game: g.game,
  });

  const scene3 = new g.Scene({
    game: g.game,
    assetPaths: ["/assets/audio/se"],
  });

  scene1.onLoad.add(() => {
    const audio = scene1.asset.getAudio("/assets/audio/se");
    audio.play();
    scene1.setTimeout(() => {
      g.game.replaceScene(scene2);
    }, 1000);
  });

  scene2.onLoad.add(() => {
    scene2.setTimeout(() => {
      g.game.replaceScene(scene3);
    }, 1000);
  });

  scene3.onLoad.add(() => {
    const audio = scene3.asset.getAudio("/assets/audio/se");
    audio.play();
  });

  g.game.pushScene(scene1);
};
```

## 備考
- 再生完了後に遷移したとしても、途中参加者によるスキップ処理で発生し得る
- 2つ目のSceneで同一のAudioAssetを読み込ませた場合は発生せず
- Scene遷移前に`.stop()`で再生を止めることで対処可能

**Comment by xnv** [comment]
詳細なご報告ありがとうございます。手元で現象を再現できました。見る限りエンジンの不具合のようです。AudioAsset は、シーンの遷移時に再生中だった場合に破棄を遅延したり、さらに遅延中に改めて必要になったら破棄をキャンセルしたりするのですが、その過程で一部データの整合性が崩れてしまっているようです。

修正を進めますが、暫定的にこのトラブルを回避いただく方法としては、次のどちらかが使えるかと思います:

- (a) グローバルアセットにする
- (b) `getAudio()` (パスによる取得) ではなく `getAudioById()` (ID による取得) を使う

(a) は、 game.json の `/assets/audio/se` のアセット宣言に 、次のように `"global": true,` という指定を追加して、当該アセットをグローバルアセットにするものです。

```json
{
  "中略": "...",
  "assets": {
    "/assets/audio/se": {
      "type": "audio",
      "path": "assets/audio/se", // 当該のアセット
      "global": true, // ←これを追加
      "その他の値": "..."
    }
  }
}
```

[グローバルアセット](https://akashic-games.github.io/guide/game-json.html#:~:text=%E3%82%B0%E3%83%AD%E3%83%BC%E3%83%90%E3%83%AB%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88) はゲーム開始時から (各シーンで指定せずとも) ずっとロードされているアセットです。そのため AudioAsset の破棄 (のキャンセル) に関連する今回のトラブルを回避できます。代償として、不要なシーンでもずっとそのアセットはロードされっぱなしになりますが、.js 側を変更せずに対処できるので暫定対処としてはこれが一番良さそうです。

別の方法としては、(b) `getAudioById()` を使う方法があります。確認したところ、 `getAudio()` がおかしくなる状況でも、 `getAudioById()` は動作するためです。ただ、[`assets/` ディレクトリに置いた時のアセット ID は不定とさせていただいている](https://akashic-games.github.io/tutorial/v3/assetPaths.html#:~:text=%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88%20ID%20%E3%82%92%E4%BF%9D%E8%A8%BC%E3%81%97%E3%81%BE%E3%81%9B%E3%82%93)
 ため、この方法を使うには `audio/` ディレクトリにファイルを移動する必要がありますし、また .js 側も変更が必要になります。

**Comment by dff9th** [comment]
丁寧なご回答ありがとうございます。
グローバルアセットについては認識していなかったため大変参考になりました。
お勧めの通り、(a) パターンにて対処しようと思います。
