### ISSUE TITLE
BGMの音量が変更できない場合がある

### ISSUE THREAD

**Issue by pkpkTech** [akashic-games/akashic-engine#381]
BGMアセットを再生する前に、BGMの全体音量を0に設定すると、その後音量を上げても音が鳴りません。
音量を0にする前に一度0より高く設定したり、BGMを再生してから音量を0にした場合は正常に音量の変更が行なえます。
BGMではなく効果音アセットの方は初めに音量を0にしても正常に再生されます。

## 環境
akashic-engine: `3.4.1`
akashic-sandbox: `0.17.47` 
akashic-cli: `2.15.66`
実行コマンド: `akashic serve --target-service nicolive` および `akashic-sandbox`
ブラウザ: `Google Chrome 102.0.5005.63`  `Firefox 100.0.2`

### 音が鳴らないコード
```
scene.onLoad.add(() => {
    const musicAsset = scene.asset.getAudioById("bgm");

    g.game.audio.music.volume = 0;
    musicAsset.play();

    scene.onPointDownCapture.add(() => {
        if (g.game.audio.music.volume < 0.5)
            g.game.audio.music.volume += 0.1;
    });
});
```
### 音が鳴るコード
```
scene.onLoad.add(() => {
    const musicAsset = scene.asset.getAudioById("bgm");

    g.game.audio.music.volume = 1;
    g.game.audio.music.volume = 0;
    musicAsset.play();

    scene.onPointDownCapture.add(() => {
        if (g.game.audio.music.volume < 0.5)
            g.game.audio.music.volume += 0.1;
    });
});
```

**Comment by xnv** [comment]
詳細な再現条件ありがとうございます。問題を確認できました。対応します。

**Comment by xnv** [comment]
この件すみません、続報がありませんでしたが修正済みです。念のため現状最新の akashic-cli@2.16.4, akashic-sandbox@0.21.0 で再現しないことを確認しました。

**Comment by xnv** [comment]
クローズします。
