### ISSUE TITLE
EventFilterに関する質問です

### ISSUE THREAD

**Issue by mujurin1** [akashic-games/akashic-engine#449]
`g.game.addEventFilter`で利用するイベントフィルターについての質問です。
COEライブラリを詳しく調べていてどうしても分からない部分、確信が持てない部分があるので質問します。

a, bの２通りの条件でイベントフィルターが呼ばれるかどうかについてと、それを元にQ1,Q2の２つの質問です。
a, bの説明自体が間違っていればその指摘もお願いします。

a. local:falseのイベントの場合
ローカルでないシーンのローカルでないエンティティRECTをクリックした時に`g.PointDownEvent (local:false)`が生成されて、`g.game.isActiveInstance()`が`true`のゲームインスタンスのイベントフィルターにこのイベントが渡されます。
この時にイベントフィルターで除外されなければ、全てのゲームインスタンスでRECTのonPointDownに登録されている関数が呼び出されます。

b. local:trueのイベントの場合
ローカルなエンティティRECTをクリックした時に`g.PointDownEvent (local:true)`が生成されて、クリックしたゲームインスタンスのイベントフィルターにこのイベントが渡されます。
この時にイベントフィルターで除外されなければ、クリックしたゲームインスタンスでRECTのonPointDownに登録されている関数が呼び出されます。

疑問に思ったのは a の場合で、`g.game.isActiveInstance()`が`true`のゲームインスタンスは、イベントフィルターが呼び出されるが、その後に受け取ったプレイヤーはイベントフィルターが呼び出されないことです。
b の場合にはクリックしたプレイヤー自身のイベントフィルターが呼び出されるので、a の場合にも呼び出されない理由に付いて次のことをを知りたいです。
Q1. なぜイベントフィルターが呼び出されないのか。
Q2. （ゲームエンジンが）何を元にイベントフィルターを呼び出すかを判断しているのか。

**Comment by xnv** [comment]
a, b について、正しく動作を理解されていると思います。

> Q1. なぜイベントフィルターが呼び出されないのか。

イベントフィルタは元々「全ゲームインスタンスに通知されるイベント (＝非ローカルなイベント) を、通知前に取捨選択する」ために作られた機能だからです。ローカルイベントを扱えるのは現状 "おまけ" という側面が強いです。

> Q2. （ゲームエンジンが）何を元にイベントフィルターを呼び出すかを判断しているのか。

アクティブインスタンス (`g.game.isActiveInstance()` が `true` のインスタンス) のイベントフィルタだけが呼ばれます。例外的に、ローカルイベントに限り、アクティブインスタンスに送られないので、一貫性のためにローカルのイベントフィルタに渡されます。

……と簡潔にお答えしましたが、これは恐らく Akashic Engine のイベント処理フローに関する疑問かと思います。Akashic Engine のイベントは (非ローカルなイベントの場合) 次のような流れで処理されます。

- A) 各プレイヤーが各ゲームインタンスで画面をクリックする
- B) 各ゲームインスタンスが、クリックに応じたイベントを生成し、アクティブインスタンスに送信する
- C) アクティブインスタンスが、送られてきたイベントを定期的にまとめて、ティック (1フレーム分の時間経過を表す情報) として全ゲームインスタンスに配信する
- D) ティックを受け取った各ゲームインスタンスが、そこに含まれるイベントを処理する
- E) 結果として各ゲームインスタンスで `onPointDown` のハンドラが呼ばれる

イベントフィルタは元々、この (C) に割り込む機能です。全ゲームインスタンスに配信する "前" に、要らないイベントを間引いたりするのに使います。(間引かなくても各ゲームインスタンスが無視すればいいのですが、通信量を減らすことができます)　そのためアクティブインスタンスのイベントフィルタだけが使われます。

ただこのフローには例外があり、それがローカルイベントです。ローカルイベントは自分にしか送られないイベントなので、通信量に関係せず、間引く必要もありません。そもそもアクティブインスタンスに送られないので、普通の ((C) の) イベントフィルタにはかけようもありません。そのため単純に「イベントフィルタ非対応」としてもよかったのですが、将来の応用の可能性を考え、「ローカルイベントは、それが発生したゲームインスタンス自身のイベントフィルタに渡す」という挙動になっています。

この経緯から、上でお答えしたような動作になります。

**Comment by mujurin1** [comment]
ありがとうございます。
知りたかったことは全て分かりました！

**Comment by mujurin1** [comment]
すみません。
最初に質問した内容は理解出来たのですが、関連する内容でもう３つ質問があります。

Q1. `g.game.raiseTick`に渡されたイベントはイベントフィルターを無視してブロードキャストされています。
これと比較して、`g.game.raiseEvent`に渡されたイベントはイベントフィルターを通した後にブロードキャストされています。
この認識は正しいでしょうか？

Q2. アクティブインスタンス以外での`g.game.raiseTick`の呼び出しは無視されるという認識で正しいでしょうか？
「無視される」というのはそもそもこのメソッドの呼び出しがなかったことになる。というレベルでの無視です。
アクティブインスタンス以外では実際に無視されているような動作に見えました。

Q3. COEフレームワークのコードで、src/impl/Scene.tsの`raiseTickIfMessageEventExists`関数で`g.game.raiseTick`を使っています。
配列の最初に`g.TimestampEvent`を渡している理由は何でしょうか？
最初に`g.TimestampEvent`が合ってもなくても同じような動作をしているように見えます。
（AkashicEngineでのTimestampの扱いや意味を余り理解出来ていないのがこれが分からない原因かもしれないです）

不要かもしれないですが、補足として、自分のテストコードでは、全て`g.MessageEvent`でテストしました。

**Comment by xnv** [comment]
> Q1. g.game.raiseTickに渡されたイベントはイベントフィルターを無視してブロードキャストされています。
> これと比較して、g.game.raiseEventに渡されたイベントはイベントフィルターを通した後にブロードキャストされています。
> この認識は正しいでしょうか？

正しいです。

(イベントフィルタは、それ単体でもフィルタとして使えますが、別の見方をするとアクティブインスタンスへの「入力」と考えることができます。一方 `raiseTick()` はアクティブインスタンスからの「出力」です。)

> Q2. アクティブインスタンス以外でのg.game.raiseTickの呼び出しは無視されるという認識で正しいでしょうか？

はい、無視されます。

> Q3. COEフレームワークのコードで、src/impl/Scene.tsのraiseTickIfMessageEventExists関数でg.game.raiseTickを使っています。
> 配列の最初にg.TimestampEventを渡している理由は何でしょうか？

これは時間情報を再現するためです。COE を利用する場合、 `Controller#broadcast()` (を通じて `raiseTick()`) しないとティックが生成されないので、受信側は次に来るティックが「いつ消費されるべきだったのか」の情報がありません。それを補うためにあります。実際のところ、普通のゲーム実行時にはほぼ関係ありません (ティックを受信したら即座に処理するので)。

akashic serve の [Playback ツール][serve-playback-devtool] のプログレスバーを戻して、過去のプレイ状況を閲覧する場合など、ティックに「いつの処理なのか」の情報がないと困る局面で利用されます。

(このあたりのめんどくさい事情 (e.g. 「アクティブインスタンス以外で raiseTick() したらどうなるのか？」とか) を意識しなくていいよう、隠蔽する存在として COE を作ったという背景があります)

[nicolive-ts]: https://qa.nicovideo.jp/faq/show/738?back=front%2Fcategory%3Ashow&category_id=521&page=1&site_domain=default&sort=sort_access&sort_order=desc
[serve-playback-devtool]: https://akashic-games.github.io/tutorial/v3/multiplay/snapshot.html#playback-devtool

**Comment by mujurin1** [comment]
ありがとうございます。
これでイベントに関することは全部分かりました。
