### ISSUE TITLE
「単なる画像」を扱うエンティティクラスが欲しい

### ISSUE THREAD

**Issue by ndxbn** [akashic-games/akashic-engine#7]
## 発端
画像を示すエンティティで、`resizeTo()` などした場合には、「指定したサイズに画像のスケールを変更する」という意味になるようなクラスが欲しいです。

`g.Sprite` クラスは、アトラス画像を扱うクラスなので `resizeTo()` などを使った場合、surface ではなく、「アトラス画像全体のサイズ」を変更するような動作をします。これは、おそらく意図通りだと思います。

しかし、単なる1つの画像を扱いたい場合は、 `resizeTo()` したら「画像を、指定したサイズで表示し直したい」という意図になると思います。

例えば、
```TypeScript
const image = new g.Image({scene: scene, src: scene.assets["asset_id"] });
image.resizeTo({x: 100, y: 100});
image.modified();
```
とした場合は、元の画像のサイズが何であれ、「100x100のサイズで、その画像を表示したい」のではないかと思います。

`g.Sprite` でこれを実現しようと思った場合には、[`scale() メソッド](https://akashic-games.github.io/reference/akashic-engine/classes/_lib_main_d_.g.sprite.html#scale) を使用するしかなく、不便だと思います。

**Comment by ndxbn** [comment]
PRは、作ってます。

**Comment by ndxbn** [comment]
外部モジュールとして作って公開したほうがいいきがしました。
お騒がせしてすみませんでした。

**Comment by xnv** [comment]
既に close されていますが、 `g.Sprite` の `srcWidth`, `srcHeight` では不足でしょうか。
次のコードは、 シーン `scene` に属する画像アセット `"anImage"` の全体を 100x100 で描画するエンティティを生成します。

```
    var sprite = new g.Sprite({
      scene: scene,
      src: scene.assets["anImage"],
      srcWidth: scene.assets["anImage"].width,
      srcHeight: scene.assets["anImage"].height,
      width: 100, 
      height: 100, 
    }); 
```

`resizeTo()` も機能すると思いますが、ただし `modified()` ではなく `invalidate()` が必要になるかと思います。

API リファレンスも併せてご覧ください。 https://akashic-games.github.io/reference/akashic-engine/classes/_lib_main_d_.g.sprite.html#srcheight
